nome: gerar animação

em:
  # executar automaticamente a cada 24 horas
  horário:
    - cron: "0 */24 * * *" 
  
  # permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch:
  
  # executar em cada push na ramificação mestre
  empurrar:
    filiais:
    - senhor
    
  

empregos:
  gerar:
    runs-on: ubuntu-mais recente
    minutos de tempo limite: 10
    
    passos:
      # gera um jogo de cobra a partir de um gráfico de contribuições de um usuário do github (<github_user_name>), produz uma animação svg em <svg_out_path>
      - nome: gerar github-contribuição-grade-cobra.svg
        utiliza: Platane/snk/svg-only@v2
        com:
          github_user_name: ${{ github.repository_owner }}
          saídas:
       dist/github-contribuição-grade-cobra.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # empurrar o conteúdo de <build_dir> para uma ramificação
      # o conteúdo estará disponível em https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , ou como página do github
      - nome: empurre github-contribution-grid-snake.svg para a ramificação de saída
        usa: crazy-max/ghaction-github-pages@v3.1.0
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
